### ISSUE TITLE
Output proper ISO-8601 strings

### ISSUE THREAD

**Issue by olvlvl** [ICanBoogie/DateTime#16]
PHP's `DateTime::ISO8601` format is not compatible with ISO: http://php.net/manual/en/class.datetime.php#datetime.constants.iso8601

> This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons. Use DateTime::ATOM or DATE_ATOM for compatibility with ISO-8601 instead.

Fix PHP's mistake and output a proper ISO-8601 string.

**Comment by Overtonesinger** [comment]
**GODlike**!
