### ISSUE TITLE
Cannot instantiate interface ICanBoogie\DateTime

### ISSUE THREAD

**Issue by Overtonesinger** [ICanBoogie/DateTime#17]
```
<?php
require __DIR__ . '/vendor/autoload.php';
date_default_timezone_set('EST'); // set local time zone to Eastern Standard Time
$time = new ICanBoogie\DateTime('now', 'Europe/Paris');
```

produces:

**PHP Fatal error:  Cannot instantiate interface ICanBoogie\DateTime in /home/xxx/xxx/src/xxx_test.php on line 4**

on PHP ver 5.6:
```
$ php --version
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

 _"Why is that, Lion?"  -_  **Blade Runner**

Any work-around on **how** can I avoid triggering this ERROR, please?

I think: At this point it would be wise to rename the class to something else than "**DateTime**", because it seems to be a keyword in **PHP 5.6**+ , which ignores namespace!  ... PHP assumes that EVERY {or THE only ONE} class called "DateTime" implements the interface...  but at the same time, it **FORBIDS** to implement it to **userland classes**!

P.S. This interface exists from PHP ver.:
**5.5.8**	_Trying to implement DateTimeInterface raises a fatal error now. Formerly implementing the interface didn't raise an error, but the behavior was erroneous._
source: [php.net/manual/en/class.datetimeinterface.php](http://php.net/manual/en/class.datetimeinterface.php)
Edit: replaced stars "*" with "x" in my path to the file.

**Comment by olvlvl** [comment]
If you're using the `2.0` branch, `ICanBoogie\DateTime` is an interface, you need to instantiate either `ICanBoogie\ImmutableDateTime` or `ICanBoogie\MutableDateTime`, depending on what you wanna do with the instance, e.g. is it mutable?.

**Comment by Overtonesinger** [comment]
It is mutable. I will probably want to change it's timezone. Is this even a mutation? :-)
_Thanx for the info!_

**Comment by olvlvl** [comment]
If it's mutable use `ICanBoogie\MutableDateTime`.
