### ISSUE TITLE
Organize coding style

### ISSUE THREAD

**Issue by peter279k** [ICanBoogie/DateTime#24]
If possible, this issue should be considered to unify coding style for this package.

Here are two coding style tools to be candidates.

- [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer)
- [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

@olvlvl, do you have any preference about this? Which coding style do you want to prefer?

I think we can consider using the [PSR-2](https://www.php-fig.org/psr/psr-2/) coding style for this package.

**Comment by olvlvl** [comment]
ICanBoogie doesn't follow PSR-2, doesn't have getter/setter public functions, and uses snake cases e.g.`->is_future`. It doesn't really fit. If we want to add style checking we need to have rules that match the current usages.

**Comment by peter279k** [comment]
> ICanBoogie doesn't follow PSR-2, doesn't have getter/setter public functions, and uses snake cases e.g.`->is_future`. It doesn't really fit. If we want to add style checking we need to have rules that match the current usages.

Thanks for your reply, @olvlvl.

I think we can choose one of coding style and customized our coding style rule for this package :).

**Comment by olvlvl** [comment]
I use code sniffer regularly, we can go with this one.
