### ISSUE TITLE
Deprecation notices from newer PHP versions

### ISSUE THREAD

**Issue by Philipp91** [ICanBoogie/DateTime#26]
```
1x: Return type of ICanBoogie\DateTime::format($format) should either be compatible with DateTime::format(string $format): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
1x in AuthApiTest::testExpiredToken from App\Auth

1x: Return type of ICanBoogie\DateTime::setTimezone($timezone) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
1x in AuthApiTest::testExpiredToken from App\Auth

1x: Return type of ICanBoogie\DateTime::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
1x in AuthApiTest::testExpiredToken from App\Auth
```

Suppressing these apparently requires support for PHP attributes, and fixing them requires support for PHP return type declarations. Presumably neither of these are available in PHP 5.6, so this would necessitate a breaking release where this library starts requiring a newer PHP version.

(Side question: Given a newer PHP's native `\DateTime` implementation, is there even any reason to use this library on top anymore? I'm asking because I see little activity on this repository.)

**Comment by olvlvl** [comment]
Hi Philipp, I just published v2.0 it should fix the issue.

**Comment by Philipp91** [comment]
Thank you!

Deprecation warnings are gone. The release is "breaking" in another way though: It used to be possible (somehow) to pass an existing `\DateTime` instance to the constructor, which would result in a clone. I guess that was mostly useful when the variable's type was unclear (like `string|\DateTime`). Now this results in an error of course:

```
TypeError: ICanBoogie\DateTime::__construct(): Argument #1 ($time) must be of type string, ICanBoogie\DateTime given, called in ...
```

I'd say it's a fair error, but should be listed in the "Backward Incompatible Changes" section.

**Comment by olvlvl** [comment]
PHP's `DateTime` only accepts strings as well on PHP 7.3+ I added a note in [MIGRATION](https://github.com/ICanBoogie/DateTime/commit/57478fb233e2f26dda7c565644fff7b938629c69). You can use `::from()` instead. Thanks for your feedback.
